
Cypress.Commands.add('fillMandatoryFieldsAndSubmit', (firstName, lastName, email, phone, text)=>{
    cy.get('#firstName')
        .type(firstName, {delay: 0})
    cy.get('#lastName')
        .type(lastName, {delay: 0})
    cy.get('#email')
        .type(email, {delay: 0})
    cy.get('#phone')
        .type(phone, {delay: 0})
    cy.get('#open-text-area')
        .type(text, {delay: 0})
    cy.contains('.button', 'Enviar')
        .click()
})

Cypress.Commands.add('fillMandatoryFieldsAndClear', (firstName, lastName, email, phone, text) =>{
    cy.get('#firstName')
        .type(firstName, {delay: 0})
        .clear()
        .should('have.value', '')
    cy.get('#lastName')
        .type(lastName, {delay: 0})
        .clear()
        .should('have.value', '')
    cy.get('#email')
        .type(email, {delay: 0})
        .clear()
        .should('have.value', '')
    cy.get('#phone')
        .type(phone, {delay: 0})
        .clear()
        .should('have.value', '')
    cy.get('#open-text-area')
        .type(text, {delay: 0})
        .clear()
        .should('have.value', '')
})